### ISSUE TITLE
Token request get rejected with self-signed certificates

### ISSUE THREAD

**Issue by vroad** [SohoHouse/nuxt-oauth#28]
Token request gets rejected because of self-signed certificates in development environment, and I don't know how to disable SSL certificate verification. The browser redirects to authenticate page again when nuxt-oauth fails to obtain token from token endpoint, so I didn't know what happened until I attach debugger to node. Setting `NODE_TLS_REJECT_UNAUTHORIZED` does not seem to have an effect on this behavior.

nuxt-oauth depends on client-oauth2, and client-oauth2 depends on popsicle for http request. I guess I need to set `rejectUnauthorized` of popsicle http transport to false in some way, but how? I need this for development environment.

https://github.com/mulesoft/js-client-oauth2
https://github.com/serviejs/popsicle

**Comment by samtgarson** [comment]
Closing as stale.
