### ISSUE TITLE
How to refresh access token from client side?

### ISSUE THREAD

**Issue by vroad** [SohoHouse/nuxt-oauth#34]
It seems that access token is refreshed only when the page is rendered on server side.
How to manually refresh access token from client, so that I could get new one before expiration?

Even on server side, current code does not seem to get new token *before* expiration. It refreshes token *after* expiration. If you only have one second left before expiration, there is a chance of authentication failures.

**Comment by Decipher** [comment]
@vroad Did you ever come up with a solution?

**Comment by samtgarson** [comment]
Hey team, this was released in v2.5. You can send a request to `/auth/refresh` to refresh your session with the OAuth provider and get a new bearer token.
