### ISSUE TITLE
dynamic path to $login()

### ISSUE THREAD

**Issue by ruchitabavishi** [SohoHouse/nuxt-oauth#42]
hi,

Right now the $login() will redirect to the auth/login path, can we change that?
ls there any way we can pass the route $login(somepath) 

Please help me with this

**Comment by samtgarson** [comment]
Hey @ruchitabavishi, currently the login path is fixed. Could you explain what you are trying to achieve? I can't picture a scenario where you'd need this. Thanks

**Comment by ruchitabavishi** [comment]
actually our website runs multiple projects and we have different repositories, for that, we have a configuration where we define which path needs to route to which repo, so here auth/login is a very generic path and it can be there in multiple projects (even if this same lib is used by some other project) then it will be difficult to define where to route auth/login.  that was the reason I raised the ticket, but right now we don't need this feature. we are able to achieve the functionality we need. Thank you for the help! :)
